### ISSUE TITLE
Authentication handling

### ISSUE THREAD

**Issue by betalb** [logux/protocol#3]
From spec perspective I see that blank spots in terms of auth handling

1) Why would `connected` message return `credentials` back in options. At least this is how I can read this statement from the docs https://github.com/logux/protocol/blame/b88b72dbf60230c63521748d27bc67b9b3bbbcb8/spec.md#L140
2) How to handle short lived tokens, is it safe/sane to do disconnect and then connect with new token

**Comment by ai** [comment]
> Why would connected message return credentials back in options.

`connected` could have a server’s credentials. It is a way for a client to verify the server. Current Logux implementation doesn’t use it.

I fixed docs 2826ca2. Is it cleaner now?

**Comment by ai** [comment]
> How to handle short lived tokens, is it safe/sane to do disconnect and then connect with new token

Yeap, you can disconnect and connect again.

But can you tell me more about it? (It is not good to disconnect too often because of UX)

**Comment by betalb** [comment]
`connected` message is cleaner now, thank you

Regarding connect / disconnect. I'm trying to figure it how to authenticate client in cases when client uses short lived JWT to authenticate

In our case ttl of token is around 5 minutes. Considering that token is pretty big in size I would like to avoid sending it with every message and instead authenticate only when token is going to expire.

That's why I'm searching for a clean way to pass the auth token. Right now it seems that the only way to re-authenticate is to re-connect. Possibility to pass authentication with any type of message might be useful, in this case we can use this info to re-authenticate client if auth is passed or use existing authentication if it is omitted.

I'm also looking at other alternatives, i.e. using higher-level protocol like STOMP to transfer messages and implement authentication logic there, not on logux level

**Comment by ai** [comment]
> In our case ttl of token is around 5 minutes.

What is a reason for so short TTL in tokens? Tell me more about your use case?

> That's why I'm searching for a clean way to pass the auth token. 

It is not the only problem of short TTL tokens.

In the real world, some low-power devices with a bad connection can spend more than 5 minutes trying to get the connection (remember you in a subway of Saint Peterburg, when you are trying to get a connection on the stations between no-signal in a tunnel).

> I'm also looking at other alternatives, i.e. using higher-level protocol like STOMP to transfer messages and implement authentication logic there, not on logux level

Yeap. You can replace protocol by defining new `Connection` and pass it to server and client.

What will be the difference between STOMP and Logux protocol? I found that message types are pretty identical.

**Comment by betalb** [comment]
> What is a reason for so short TTL in tokens? Tell me more about your use case? 

JWT tokens by design are not revokable (even though technically it is possible), so this is security measure

> It is not the only problem of short TTL tokens.
> 
> In the real world, some low-power devices with a bad connection can spend more than 5 minutes trying to get the connection (remember you in a subway of Saint Peterburg, when you are trying to get a connection on the stations between no-signal in a tunnel).

It is not that bad at the moment ;)

But such connection issues won't cause problems once token will be reissued messages will continue to flow. But I agree in terms of latency, this seems an overkill for general use case. Our use case allows this

> What will be the difference between STOMP and Logux protocol? I found that message types are pretty identical.

Looks like I haven't read spec carefully, will check how to pass arbitrary metadata with messages

**Comment by ai** [comment]
> JWT tokens by design are not revokable (even though technically it is possible), so this is security measure

It is not a use case. Tell me more about an application, UI and what users do exactly.

Are you sure that JWT fits your case? All methods that I saw require more LOC, longer connection process and could have some unexpected UX problems.

Possible solution:

1. HTML page of the application contains short-time JWT token.
2. After you will be connected to Logux Server, Logux Server will send new JWT token every 5 minutes (bad, because it will spend a lot of bandwidth). Or instead of sending a new token every 5 minutes, we can request a new token before Logux will connect to the server (but it will slow down the re-connection process)
3. If the client didn’t connect for that 5 minutes, the app will request a new token for Logux (ba because we need to write code for this custom behavior).

The main security problem in this way is that you already have long-live cookie token. So using short-time Logux tokens will not increase security, because you use old-style long-live cookie tokens.

**Comment by betalb** [comment]
> It is not a use case. Tell me more about an application, UI and what users do exactly.

In a nutshell – this is realtime graph editing application with collaborative features, intended for desktop usage in web browser. I think the closest analogue is diagram editing app where several users can concurrently modify the same diagram. This is web app communicating with a set of micro-services through reverse proxy (passive proxy that is not aware of authentication and all that stuff).

This is only small part of app in general. Other parts do not require logux and use REST API.

> Are you sure that JWT fits your case? All methods that I saw require more LOC, longer connection process and could have some unexpected UX problems.

LOC – that's what we've being payed for :)
But right now we mitigated all UX issues with short living tokens, and feel comfortable with them.

> The main security problem in this way is that you already have long-live cookie token. So using short-time Logux tokens will not increase security, because you use old-style long-live cookie tokens.

You are right, there is a long living token (in cookie), but important part is that it is bound to domain of Auth server which I "trust", and for the rest of services that I don't trust (there are several dozens of them) we use short living tokens, because I don't know how this token will be used (they can store it, resend to some other services instead of using OIDC token exchange, etc.)

But it looks like that all of the above is external to protocol itself and should be implemented as middleware on server level. And even default logux server should not provide something out of the box, because Authn/z is always a pain question, it should just provide pointcuts where custom logic can be plugged

**Comment by ai** [comment]
What do you think about this solution:

1. You use old cookie token in Logux.
2. Logux Server doesn’t authenticate users. It just creates HTTP request to old Auth server to verify cookie token. If the server authenticates user, Logux Server will pass the client.

Benefits:

1. Your auth system is small and based on this single auth logic. Having one logic is much better in terms of security.
2. You do not have any UX problems. Re-connection time will be short. The app will still support offline.
3. You do not need to write a lot of code.

**Comment by betalb** [comment]
Thank you, I was going to implement something along this lines
